select TRY_CAST(DDATE AS DATE) AS DDATE
       ,SALESPERSON
       ,CUSTOMERNAME
       ,CARMAKE
       ,CARMODEL
       ,TRY_CAST(CARYEAR AS INT) YEAR
       ,SALEPRICE
       ,COMMISSIONRATE AS COM_RATE
       ,COMMISSIONEARNED AS COM_EAR
from {{source("raw_bi_car","CAR_SALES") }} WHERE TRY_CAST(DDATE AS DATE) > '2020-01-01'