-- ESTE TEST PASA SI ESTA CONSULTA DEVUELVE CERO FILAS
-- SELECCIONE CUALQUIER REGISTRO DE LA TABLA DE HECHOS DONDE LAS METRICAS CLAVE SEAN NEGATIVAS

SELECT DDATE , 
       ID_SALESPERSON,
       ID_CARMAKE,
       TOTAL_SALE,
       TOTALCOM
FROM {{ ref('fct_monthly_sales')}}
where TOTAL_SALE < 0 OR TOTALCOM < 0